### PR TITLE
fix: stop building image

### PR DESCRIPTION
**Pull request by msvticket**
when using the jx-changelog image the command jx changelog download jx-changelog anyway (can be avoided by using of jx-changelog instead)

depends on #49 and jenkins-x/jx3-pipeline-catalog#1339

### CODE REVIEW

**Comment by ankitm123** [comment]
Remove the dockerfile, otherwise looks good to me.

**Comment by msvticket** [comment]
> Remove the dockerfile, otherwise looks good to me.

Images are still built for pull requests, so the Dockerfile is still in use

**Comment by ankitm123** [comment]
> > Remove the dockerfile, otherwise looks good to me.
> 
> Images are still built for pull requests, so the Dockerfile is still in use

Is there a reason we want to keep building images in PR?

**Comment by msvticket** [comment]
To ease manual testing

**Pull request merged**
